# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python:
  - "2.7"
  - "3.6"
env:
  - TOX_ENV=py36
  - TOX_ENV=py27

script: tox

install:
    - pip install tox-travis
